### ISSUE TITLE
free.lsmdiskgrp.[mdiskgrp0]  -> Value of type "string" is not suitable for value type "Numeric (unsigned)". Value "None"

### ISSUE THREAD

**Issue by Mahmoudwardeh** [aklyuk/zabbix-ibm-storwize#11]
hello everyone, can someone please help me, 
when I run the script I get a "2" and then in Zabbix I get these errors "ree.lsmdiskgrp.[mdiskgrp0] -> Value of type "string" is not suitable for value type "Numeric (unsigned)". Value "None""
what can i do?

**Comment by GitCoastn** [comment]
Hi, had the same issue, please have a look here: https://github.com/GitCoastn/zabbix-ibm-storwize/commit/2adb7890282926c208c43839000a222b34890262

**Comment by Mahmoudwardeh** [comment]
Done!
