### ISSUE TITLE
Discovery doesn't work

### ISSUE THREAD

**Issue by portatip** [aklyuk/zabbix-ibm-storwize#2]
Zabbix 4.0.9
Python 2.7
ServerActive=127.0.0.1 in /etc/zabbix/zabbix_agentd.conf on server
storwize_state.log chmod 777, owner - zabbix
storwize_get_state.py chmod 755, owner - zabbix
_./storwize_get_state.py  --storwize_ip=192.168.16.5 --storwize_port=22 --storwize_user=admin --storwize_password='password' --storage_name="storage_name_in_zabbix" --discover_ retuns "2"
In "Latest Data" "get discovery" returns 1
![image](https://user-images.githubusercontent.com/54619629/69807060-6527fa80-11f5-11ea-9da9-b4e91bec615d.png)
Thanks!

**Comment by portatip** [comment]
[Log](https://pastebin.com/zmp7AQ4i)

**Comment by aklyuk** [comment]
exit status 0 or 1 or 2 is zabbix_sender exit status.

_EXIT STATUS
The exit status is 0 if the values were sent and all of them were successfully processed by server. If data was sent, but processing of at least one of the values failed, the exit status is 2. If data sending failed, the exit status is 1._

**Comment by portatip** [comment]
Can you explain what's "storage_name"?

**Comment by aklyuk** [comment]
storage_name is name of storage in zabbix web interface

**Comment by portatip** [comment]
Yey! I modified key in template without macros and got something like this 
`storwize_get_state.py["--storwize_ip=192.168.16.55","--storwize_port=22","--storwize_user=admin","--storwize_password=123456","--storage_name=192.168.16.55","--discover"]`
Now works good. Thanks for the work you've done!
